plugins {
    alias(libs.plugins.protobuf)
}

description = 'The compiled directed mesh runtime, demand-driven processor transport, durable channel, and settlement protocol'

dependencies {
    api libs.protobuf.java
    api libs.protobuf.java.util
    api libs.grpc.api
    api libs.grpc.stub
    api libs.grpc.protobuf
    api project(':protomolt-mesh-runtime-proto')
    api project(':protomolt-mesh-contracts')
    api project(':protomolt-mesh-cluster')
    implementation project(':protomolt-repo-proto')
    api project(':protomolt-projection')
    implementation project(':protomolt-mapper-cel')
    implementation project(':protomolt-shapes')
    implementation project(':protomolt-descriptors')
    api project(':protomolt-protobuf-validation')
    api project(':protomolt-protobuf-metadata')

    compileOnly libs.javax.annotation.api
    testImplementation libs.grpc.inprocess
    testImplementation libs.postgresql
    testImplementation libs.testcontainers.junit.jupiter
    testImplementation libs.testcontainers.postgresql
    protobuf project(':protomolt-mesh-runtime-proto')
}

protobuf {
    protoc {
        artifact = "com.google.protobuf:protoc:${libs.versions.protobuf.asProvider().get()}"
    }
    plugins {
        grpc {
            artifact = "io.grpc:protoc-gen-grpc-java:${libs.versions.grpc.get()}"
        }
    }
    generateProtoTasks {
        all().configureEach {
            plugins {
                grpc {}
            }
        }
    }
}
