inference_address=http://0.0.0.0:8080
management_address=http://0.0.0.0:8080
metrics_address=http://0.0.0.0:8080
job_queue_size=8
default_workers_per_model=1
max_request_size=1048576
max_response_size=1048576
